-- Casa de la Mujer - Actividad 04
-- Ejecutar una sola vez en Supabase > SQL Editor.
-- Compatible con tablas existentes: agrega columnas faltantes y recrea políticas con nombres conocidos.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  role text not null default 'user' check (role in ('user','admin','super_admin')),
  created_at timestamptz not null default now()
);

alter table public.profiles add column if not exists role text not null default 'user';
alter table public.profiles add column if not exists created_at timestamptz not null default now();

create table if not exists public.complaints (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  type text not null,
  description text not null,
  incident_date date,
  status text not null default 'Recibida',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table public.complaints add column if not exists type text;
alter table public.complaints add column if not exists description text;
alter table public.complaints add column if not exists incident_date date;
alter table public.complaints add column if not exists status text not null default 'Recibida';
alter table public.complaints add column if not exists created_at timestamptz not null default now();
alter table public.complaints add column if not exists updated_at timestamptz not null default now();

create table if not exists public.case_updates (
  id uuid primary key default gen_random_uuid(),
  complaint_id uuid not null references public.complaints(id) on delete cascade,
  created_by uuid not null references public.profiles(id) on delete cascade,
  comment text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete set null,
  action varchar(80) not null,
  entity varchar(80) not null,
  entity_id uuid,
  details jsonb default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create or replace function public.get_my_role()
returns text language sql stable security definer set search_path = public
as $$ select coalesce((select role from public.profiles where id = auth.uid()), 'user') $$;

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public
as $$ begin insert into public.profiles(id, role) values(new.id,'user') on conflict(id) do nothing; return new; end; $$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user();

-- Sincroniza usuarios creados antes de instalar este script.
insert into public.profiles(id, role)
select id, 'user' from auth.users on conflict(id) do nothing;

create or replace function public.audit_complaint_insert()
returns trigger language plpgsql security definer set search_path = public
as $$ begin insert into public.audit_logs(user_id,action,entity,entity_id,details) values(new.user_id,'INSERT','complaints',new.id,jsonb_build_object('status',new.status,'type',new.type)); return new; end; $$;
drop trigger if exists trg_audit_complaint_insert on public.complaints;
create trigger trg_audit_complaint_insert after insert on public.complaints for each row execute function public.audit_complaint_insert();

alter table public.profiles enable row level security;
alter table public.complaints enable row level security;
alter table public.case_updates enable row level security;
alter table public.audit_logs enable row level security;

-- Policies idempotentes
DO $$ DECLARE p record; BEGIN FOR p IN SELECT policyname, tablename FROM pg_policies WHERE schemaname='public' AND tablename IN ('profiles','complaints','case_updates','audit_logs') LOOP EXECUTE format('DROP POLICY IF EXISTS %I ON public.%I', p.policyname, p.tablename); END LOOP; END $$;

create policy profiles_select_own on public.profiles for select to authenticated using (id=auth.uid());
create policy profiles_update_own on public.profiles for update to authenticated using (id=auth.uid()) with check (id=auth.uid());
create policy profiles_select_admin on public.profiles for select to authenticated using (public.get_my_role() in ('admin','super_admin'));

create policy complaints_select_own on public.complaints for select to authenticated using (user_id=auth.uid());
create policy complaints_insert_own on public.complaints for insert to authenticated with check (user_id=auth.uid());
create policy complaints_update_admin on public.complaints for update to authenticated using (public.get_my_role() in ('admin','super_admin')) with check (public.get_my_role() in ('admin','super_admin'));
create policy complaints_select_admin on public.complaints for select to authenticated using (public.get_my_role() in ('admin','super_admin'));

create policy case_updates_select_owner on public.case_updates for select to authenticated using (exists(select 1 from public.complaints c where c.id=complaint_id and (c.user_id=auth.uid() or public.get_my_role() in ('admin','super_admin'))));
create policy case_updates_insert_admin on public.case_updates for insert to authenticated with check (public.get_my_role() in ('admin','super_admin') and created_by=auth.uid());

create policy audit_logs_select_admin on public.audit_logs for select to authenticated using (public.get_my_role() in ('admin','super_admin'));

-- Índices
create index if not exists idx_complaints_user_id on public.complaints(user_id);
create index if not exists idx_case_updates_complaint_id on public.case_updates(complaint_id);
create index if not exists idx_audit_logs_entity_id on public.audit_logs(entity_id);
