import { useEffect, useState } from 'react'
import { Link } from 'react-router'
import { listMyComplaints } from '../../services/complaints'

const labels={fisica:'Violencia física',psicologica:'Violencia psicológica',sexual:'Violencia sexual',economica:'Violencia económica',laboral:'Situación laboral',otra:'Otra situación'}
export default function MyCases(){const [cases,setCases]=useState([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('')
 useEffect(()=>{listMyComplaints().then(setCases).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[])
 return <main className="min-h-screen bg-slate-50"><header className="border-b bg-white"><div className="mx-auto max-w-5xl px-4 py-5"><p className="text-sm font-semibold text-emerald-700">Casa de la Mujer</p><h1 className="mt-1 text-2xl font-bold">Mis casos</h1></div></header><div className="mx-auto max-w-5xl p-4 sm:p-6"><div className="flex justify-between gap-3"><Link to="/mi" className="text-emerald-700 underline">← Volver</Link><Link to="/mi/nueva-denuncia" className="rounded-lg bg-emerald-700 px-4 py-2 font-semibold text-white">Nueva denuncia</Link></div>
 <section className="mt-6"><h2 className="text-xl font-bold">Tus denuncias</h2>{loading&&<p className="mt-4">Cargando...</p>}{error&&<p role="alert" className="mt-4 rounded-lg bg-red-50 p-4 text-red-800">{error}</p>}{!loading&&!error&&cases.length===0&&<p className="mt-4 rounded-lg bg-white p-5">Todavía no tienes denuncias registradas.</p>}<div className="mt-4 space-y-4">{cases.map(c=><article key={c.id} className="rounded-xl border bg-white p-5 shadow-sm"><div className="flex flex-col gap-3 sm:flex-row sm:justify-between"><div><p className="text-sm text-slate-500">Código</p><h3 className="font-bold">{c.id}</h3><p className="mt-2">{labels[c.type]||c.type}</p></div><span className="h-fit rounded-full bg-amber-100 px-3 py-1 text-sm font-semibold text-amber-900">{c.status}</span></div><p className="mt-4 text-sm text-slate-600">Registrado: {new Date(c.created_at).toLocaleString('es-BO')}</p><Link to={`/mi/casos/${c.id}`} className="mt-3 inline-block font-semibold text-emerald-700 underline">Ver estado del caso</Link></article>)}</div></section></div></main>}
